version: "3"

services:
  web-app:
    build: .
    command: flask run --debug --host=0.0.0.0
    volumes:
      - .:/project-1-web-application-design-group17-jigglies
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_TOKEN}

  test:
    build: .
    command: pytest tests/
    volumes:
      - .:/project-1-web-application-design-group17-jigglies
