name: Unit Tests CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run tests
        run: docker compose up test --build # Ensure the tests are rebuilt every time
      
      - name: Clean up
        if: always()  # Ensure clean up happens even if tests fail
        run: docker-compose down
