name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        run: docker-compose up -d web-app

      - name: Run unit tests
        run: |
          docker-compose run --rm unit-tests
          docker-compose logs unit-tests

      - name: Run automation tests
        run: |
          docker-compose run --rm automation-tests
          docker-compose logs automation-tests
        
      - name: Clean up
        if: always()  # Ensure clean up happens even if tests fail
        run: docker-compose down
