name: Unit Tests CI Pipeline

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]  

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        run: |
          docker compose up web-app

      - name: Run unit tests
        run: |
          docker compose up unit-tests

      - name: Run automation tests
        run: |
          docker compose up automation tests
        
      - name: Clean up
        if: always()  # Ensure clean up happens even if tests fail
        run: docker-compose down
